name: Build Android Release APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Ignore Broken Submodules Manually
        run: |
          git config --global submodule.recurse false
          git rm --cached flutter || true

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false

      - name: Install Dependencies
        run: |
          cd app
          flutter pub get

      - name: Build APK
        env:
          FLUTTER_ROOT: ${{ env.FLUTTER_ROOT }}
          PUB_CACHE: ${{ github.workspace }}/.pub-cache
        run: |
          cd app
          flutter build apk --release --split-per-abi
          
      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dookai-release-apks
          path: app/build/app/outputs/apk/release/*.apk
          
